site_name: Documentation UEPAL Civiparoisse
site_url : https://uepal-civiparoisse-documentation.github.io/index.html
nav:
    - 'INDEX': 'index.md'
    - 'MODE D\''EMPLOI':
        - 'Index': 'UTILISATION/mode_emploi/mode_d_emploi.md'
        - '1. Introduction': 'UTILISATION/mode_emploi/1_introduction.md'
        - '2. Débuter': 'UTILISATION/mode_emploi/2_debuter.md'
        - '3. Faire des recherches sur les contacts': 'UTILISATION/mode_emploi/3_faire_des_recherches_sur_les_contacts.md'
        - '4. Envoyer un courriel': 'UTILISATION/mode_emploi/4_envoyer_un_courriel.md'
        - '5. Gestion des dons et édition des reçus fiscaux': 'UTILISATION/mode_emploi/5_gestion_des_dons_et_edition_des_recus_fiscaux.md'
        - '6. Que faire quand... ?': 'UTILISATION/mode_emploi/6_que_faire_quand.md'
        - '7. Créer et gérer un événement': 'UTILISATION/mode_emploi/7_creer_et_gerer_un_evenement.md'
        - '8. Opérations à mener régulièrement': 'UTILISATION/mode_emploi/8_operations_a_mener_regulierement.md'
        - '9. Gestion de la base de données' : 'UTILISATION/mode_emploi/9_gestion_base_donnees.md'
        - '99. Préparer l\''installation initiale de CiviParoisse' : 'UTILISATION/mode_emploi/99_prepaper_installation.md'
        - 'Les nouveautés dans CiviParoisse' : 'UTILISATION/mode_emploi/nouveautes_CiviParoisse.md'
        - 'Ressources utiles': 'UTILISATION/ressources.md'
    - 'PRESENTATION DU PROJET CIVIPAROISSE':
        - 'Introduction': 'PRESENTATION/index.md'
        - 'Périmètre fonctionnel': 'PRESENTATION/presentation_fonctionnelle.md'
        - 'Ecosystème projet': 'PRESENTATION/presentation_ecosysteme.md'
        - 'Livrables': 'PRESENTATION/presentation_livrables.md'
    - 'ELEMENTS TECHNIQUES':
       - 'PRE_POC':
           - 'Index': 'TECHNIQUE/PREPOC/index.md'
           - 'Description générale': 'TECHNIQUE/PREPOC/poc.md'
           - 'Infrastructure': 'TECHNIQUE/PREPOC/infrastructure.md'
           - 'Diff IMG Docker': 'TECHNIQUE/PREPOC/docker_diff.md'
           - 'Diff Chart Helm': 'TECHNIQUE/PREPOC/helm_diff.md'
           - 'Trafic initiateur entrant': 'TECHNIQUE/PREPOC/trafic_entrant.md'
           - 'Maquettage Traefik': 'TECHNIQUE/PREPOC/traefik.md'
           - 'Identités et certificats': 'TECHNIQUE/PREPOC/identites_certificats.md'
           - 'Web Application Firewall': 'TECHNIQUE/PREPOC/waf.md'
       - 'Rôles': 'TECHNIQUE/roles.md'
       - 'Mail':
           - 'Index': 'TECHNIQUE/MAIL/mail.md'
           - 'Ecosystème': 'TECHNIQUE/MAIL/ecosysteme.md'
           - 'Envoi': 'TECHNIQUE/MAIL/sendmail.md'
           - 'Réception': 'TECHNIQUE/MAIL/fetchmail.md'
       - 'Logiciel':
           - 'Index': 'TECHNIQUE/LOGICIEL/index.md'
           - 'Distribution de code': 'TECHNIQUE/LOGICIEL/distribution_code_composer.md'
           - 'Environnement de dev': 'TECHNIQUE/LOGICIEL/environnement_dev.md'
           - 'Personnalisation environnement de dev': 'TECHNIQUE/LOGICIEL/environnement_dev_env.md'
           - 'Importation de données': 'TECHNIQUE/LOGICIEL/importation.md'
       - 'Intégration':
           - 'Index': 'TECHNIQUE/INTEGRATION/index.md'
           - 'Authentification': 'TECHNIQUE/INTEGRATION/etude_authentification.md'
           - 'Docker': 
              - 'Description générale': 'TECHNIQUE/INTEGRATION/docker.md'
              - 'Images':
                - 'Composer_base': 'TECHNIQUE/INTEGRATION/DOCKER/composer_base.md'
                - 'Composer_files': 'TECHNIQUE/INTEGRATION/DOCKER/composer_files.md'
                - 'tools': 'TECHNIQUE/INTEGRATION/DOCKER/tools.md'
                - 'init': 'TECHNIQUE/INTEGRATION/DOCKER/init.md'
                - 'cron': 'TECHNIQUE/INTEGRATION/DOCKER/cron.md'
                - 'selfkeys': 'TECHNIQUE/INTEGRATION/DOCKER/selfkeys.md'
                - 'httpd': 'TECHNIQUE/INTEGRATION/DOCKER/httpd.md'
                - 'authenticator': 'TECHNIQUE/INTEGRATION/DOCKER/authenticator.md'
                - 'proxy': 'TECHNIQUE/INTEGRATION/DOCKER/proxy.md'
                - 'db_tls_server': 'TECHNIQUE/INTEGRATION/DOCKER/db_tls_server.md'
                - 'db_tls_client': 'TECHNIQUE/INTEGRATION/DOCKER/db_tls_client.md'
                - 'update': 'TECHNIQUE/INTEGRATION/DOCKER/update.md'
           - 'DB_SSL': 'TECHNIQUE/INTEGRATION/db_ssl.md'
           - 'Kubernetes': 
                - 'Maquettage': 'TECHNIQUE/INTEGRATION/KUBERNETES/maquettage.md'
                - 'Ressources utiles': 'TECHNIQUE/INTEGRATION/KUBERNETES/ressources.md'
                - 'Chart Helm':
                    - 'Description générale': 'TECHNIQUE/INTEGRATION/KUBERNETES/HELM/description_generale.md'
                    - 'DB et DB proxy': 'TECHNIQUE/INTEGRATION/KUBERNETES/HELM/db_dbproxy.md'
                    - 'Serveur web interne': 'TECHNIQUE/INTEGRATION/KUBERNETES/HELM/httpd.md'
                    - 'Proxy et authenticateur': 'TECHNIQUE/INTEGRATION/KUBERNETES/HELM/proxy_auth.md'
                    - 'Cron': 'TECHNIQUE/INTEGRATION/KUBERNETES/HELM/cron.md'
                    - 'Volumes (persistants)': 'TECHNIQUE/INTEGRATION/KUBERNETES/HELM/volumes.md'
                    - 'Secrets': 'TECHNIQUE/INTEGRATION/KUBERNETES/HELM/secrets.md'
                    - 'Réservations': 'TECHNIQUE/INTEGRATION/KUBERNETES/HELM/reservations.md'









theme: 
   name: material
   logo: assets/uepal-logo.svg
   locale: fr
   features:
     - search.suggest
     - search.highlight
     - navigation.sections
#     - navigation.expand
   palette:
     - scheme: slate
       toggle:
         icon: material/toggle-switch-off-outline
         name: switch to light mode
     - scheme: default
       toggle:
         icon: material/toggle-switch
         name: Switch to dark mode
   plugins:
   - search:
       lang: fr
use_directory_urls: false
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.superfences
  - toc:
     anchorlink: true
     title: 'Table des matières'
extra_css:
  - stylesheets/extra.css
