name: ci
on:
  push:
    branches:
      - master
      - main
    workflow_dispatch:
env:
  MKDOCSIMG: squidfunk/mkdocs-material
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: false
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Pull squidfunk/mkdocs-material
        run: |
         docker pull squidfunk/mkdocs-material
      - name: Render global doc
        run: |
         docker run --rm -i --mount type=bind,source=${GITHUB_WORKSPACE},destination=/docs --name="mkdocs_material"  ${MKDOCSIMG}  build -v -v -v -f global.yml
      - name: Render technical doc
        run: |
         docker run --rm -i --mount type=bind,source=${GITHUB_WORKSPACE},destination=/docs --name="mkdocs_material"  ${MKDOCSIMG}  build -v -v -v -f technique.yml
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        id: artifact-upload-step
        with:
          path: 'site'
          name:  doc-deployment-${{ github.sha }}-${{ github.run_number }}-${{ github.run_attempt }}
      - name: deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: doc-deployment-${{ github.sha }}-${{ github.run_number }}-${{ github.run_attempt }}
